### ISSUE TITLE
Using this extention

### ISSUE THREAD

**Issue by am2222** [mloskot/boost-geometry-workshop#1]
Hi, 
Does this extension works with latest boost version?
and is there any example how to compile and use it?

**Comment by mloskot** [comment]
These are just experiments. You'll need to try and see if any of these codes  work with Boost.Geometry from newer Boost

**Comment by am2222** [comment]
@mloskot thanks so much, I'll try that

**Comment by am2222** [comment]
@mloskot Hi,
I made some modifications and could make it work with the last version of boost, But I had one question. I wanted to know how is possible to convert a boost geometry object into wkb format. is there any functions which I can use it in your library?
Thanks

**Comment by mloskot** [comment]
See this

https://github.com/boostorg/geometry/tree/develop/include/boost/geometry/extensions/gis/io/wkb
https://github.com/boostorg/geometry/tree/develop/extensions/test/gis/io/wkb

Best place to ask Boost.Geometry questions is https://lists.boost.org/mailman/listinfo.cgi/geometry

**Comment by am2222** [comment]
@mloskot thanks so much
